name: build matrix demo

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8"]
        django-version: ["1.11", "2.0", "2.1", "2.2", "3.0"]
        exclude:
          # Python 2.7 is compatible with Django 1.11
          - python-version: "2.7"
            django-version: "2.0"
          - python-version: "2.7"
            django-version: "2.1"
          - python-version: "2.7"
            django-version: "2.2"
          - python-version: "2.7"
            django-version: "3.0"
          # Python 3.5 is compatible with Django <3.0
          - python-version: "3.5"
            django-version: "3.0"
          # Python 3.8 is compatible with Django 2.2+
          - python-version: "3.8"
            django-version: "1.11"
          - python-version: "3.8"
            django-version: "2.0"
          - python-version: "3.8"
            django-version: "2.1"

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Echo Python version
        run: |
          echo "${{ matrix.python-version }} -> ${{ matrix.django-version }}"
          python -m pip install -U pip
          python -m pip install "Django~=${{ matrix.django-version }}.0"
          python --version
          echo "Django: `django-admin --version`"
